

server:
  port: 8087

welcome:
  message: Welcome to the Pandora QA server!!!!

spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/major_switchQA
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true